### ISSUE TITLE
How do I start the bot?

### ISSUE THREAD

**Issue by niacobel** [herrozerro/Cypher-Bot#7]
Hello,

Thank you for sharing this project! I'm quite new to discord and I'm not really a programmer myself. I created the bot on discord and invited it in the server but ... how do I start it? I only see source code and no executables. :/

Thank you in advance for your help!

**Comment by herrozerro** [comment]
Under releases there are executables for systems.

https://github.com/herrozerro/Cypher-Bot/releases

Copy your bot token to appsettings.json

And run the executable.  You'll need to provide your own cyphers and artifacts, but there are template files in the datafiles folder.

if you need anymore help, you can post here or even send me an email and I can help.

**Comment by niacobel** [comment]
Thank you
